// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vla8islav/gophkeeper/internal/domain (interfaces: GophkeeperRepository,GophkeeperService)
//
// Generated by this command:
//
//	mockgen -destination=domain_mock.go -package=mocks github.com/Vla8islav/gophkeeper/internal/domain GophkeeperRepository,GophkeeperService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Vla8islav/gophkeeper/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGophkeeperRepository is a mock of GophkeeperRepository interface.
type MockGophkeeperRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGophkeeperRepositoryMockRecorder
	isgomock struct{}
}

// MockGophkeeperRepositoryMockRecorder is the mock recorder for MockGophkeeperRepository.
type MockGophkeeperRepositoryMockRecorder struct {
	mock *MockGophkeeperRepository
}

// NewMockGophkeeperRepository creates a new mock instance.
func NewMockGophkeeperRepository(ctrl *gomock.Controller) *MockGophkeeperRepository {
	mock := &MockGophkeeperRepository{ctrl: ctrl}
	mock.recorder = &MockGophkeeperRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophkeeperRepository) EXPECT() *MockGophkeeperRepositoryMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockGophkeeperRepository) CreateSecret(ctx context.Context, user domain.CreateSecretParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockGophkeeperRepositoryMockRecorder) CreateSecret(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockGophkeeperRepository)(nil).CreateSecret), ctx, user)
}

// CreateUser mocks base method.
func (m *MockGophkeeperRepository) CreateUser(ctx context.Context, user domain.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophkeeperRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophkeeperRepository)(nil).CreateUser), ctx, user)
}

// DeleteSecret mocks base method.
func (m *MockGophkeeperRepository) DeleteSecret(ctx context.Context, userID int64, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockGophkeeperRepositoryMockRecorder) DeleteSecret(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockGophkeeperRepository)(nil).DeleteSecret), ctx, userID, id)
}

// GetSecret mocks base method.
func (m *MockGophkeeperRepository) GetSecret(ctx context.Context, userID int64, id uuid.UUID) (*domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, userID, id)
	ret0, _ := ret[0].(*domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockGophkeeperRepositoryMockRecorder) GetSecret(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockGophkeeperRepository)(nil).GetSecret), ctx, userID, id)
}

// GetUserByLogin mocks base method.
func (m *MockGophkeeperRepository) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGophkeeperRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGophkeeperRepository)(nil).GetUserByLogin), ctx, login)
}

// GetUserSalt mocks base method.
func (m *MockGophkeeperRepository) GetUserSalt(ctx context.Context, userID int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSalt", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSalt indicates an expected call of GetUserSalt.
func (mr *MockGophkeeperRepositoryMockRecorder) GetUserSalt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSalt", reflect.TypeOf((*MockGophkeeperRepository)(nil).GetUserSalt), ctx, userID)
}

// ListSecrets mocks base method.
func (m *MockGophkeeperRepository) ListSecrets(ctx context.Context, userID int64) ([]domain.SecretSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx, userID)
	ret0, _ := ret[0].([]domain.SecretSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockGophkeeperRepositoryMockRecorder) ListSecrets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockGophkeeperRepository)(nil).ListSecrets), ctx, userID)
}

// Ping mocks base method.
func (m *MockGophkeeperRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophkeeperRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophkeeperRepository)(nil).Ping), ctx)
}

// SyncSecrets mocks base method.
func (m *MockGophkeeperRepository) SyncSecrets(ctx context.Context, userID int64) ([]domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncSecrets", ctx, userID)
	ret0, _ := ret[0].([]domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncSecrets indicates an expected call of SyncSecrets.
func (mr *MockGophkeeperRepositoryMockRecorder) SyncSecrets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncSecrets", reflect.TypeOf((*MockGophkeeperRepository)(nil).SyncSecrets), ctx, userID)
}

// UpdateSecret mocks base method.
func (m *MockGophkeeperRepository) UpdateSecret(ctx context.Context, params domain.UpdateSecretParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, params)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockGophkeeperRepositoryMockRecorder) UpdateSecret(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockGophkeeperRepository)(nil).UpdateSecret), ctx, params)
}

// MockGophkeeperService is a mock of GophkeeperService interface.
type MockGophkeeperService struct {
	ctrl     *gomock.Controller
	recorder *MockGophkeeperServiceMockRecorder
	isgomock struct{}
}

// MockGophkeeperServiceMockRecorder is the mock recorder for MockGophkeeperService.
type MockGophkeeperServiceMockRecorder struct {
	mock *MockGophkeeperService
}

// NewMockGophkeeperService creates a new mock instance.
func NewMockGophkeeperService(ctrl *gomock.Controller) *MockGophkeeperService {
	mock := &MockGophkeeperService{ctrl: ctrl}
	mock.recorder = &MockGophkeeperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophkeeperService) EXPECT() *MockGophkeeperServiceMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockGophkeeperService) CreateSecret(ctx context.Context, userID int64, req domain.CreateSecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockGophkeeperServiceMockRecorder) CreateSecret(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockGophkeeperService)(nil).CreateSecret), ctx, userID, req)
}

// CreateUser mocks base method.
func (m *MockGophkeeperService) CreateUser(ctx context.Context, request domain.UserRegisterRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophkeeperServiceMockRecorder) CreateUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophkeeperService)(nil).CreateUser), ctx, request)
}

// DeleteSecret mocks base method.
func (m *MockGophkeeperService) DeleteSecret(ctx context.Context, userID int64, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockGophkeeperServiceMockRecorder) DeleteSecret(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockGophkeeperService)(nil).DeleteSecret), ctx, userID, id)
}

// GetSecret mocks base method.
func (m *MockGophkeeperService) GetSecret(ctx context.Context, userID int64, id uuid.UUID) (*domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, userID, id)
	ret0, _ := ret[0].(*domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockGophkeeperServiceMockRecorder) GetSecret(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockGophkeeperService)(nil).GetSecret), ctx, userID, id)
}

// GetUserSalt mocks base method.
func (m *MockGophkeeperService) GetUserSalt(ctx context.Context, userID int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSalt", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSalt indicates an expected call of GetUserSalt.
func (mr *MockGophkeeperServiceMockRecorder) GetUserSalt(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSalt", reflect.TypeOf((*MockGophkeeperService)(nil).GetUserSalt), ctx, userID)
}

// ListSecrets mocks base method.
func (m *MockGophkeeperService) ListSecrets(ctx context.Context, userID int64) ([]domain.SecretSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSecrets", ctx, userID)
	ret0, _ := ret[0].([]domain.SecretSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockGophkeeperServiceMockRecorder) ListSecrets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockGophkeeperService)(nil).ListSecrets), ctx, userID)
}

// LoginUser mocks base method.
func (m *MockGophkeeperService) LoginUser(ctx context.Context, request domain.UserLoginRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockGophkeeperServiceMockRecorder) LoginUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockGophkeeperService)(nil).LoginUser), ctx, request)
}

// Ping mocks base method.
func (m *MockGophkeeperService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophkeeperServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophkeeperService)(nil).Ping), ctx)
}

// SyncSecrets mocks base method.
func (m *MockGophkeeperService) SyncSecrets(ctx context.Context, userID int64) ([]domain.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncSecrets", ctx, userID)
	ret0, _ := ret[0].([]domain.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncSecrets indicates an expected call of SyncSecrets.
func (mr *MockGophkeeperServiceMockRecorder) SyncSecrets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncSecrets", reflect.TypeOf((*MockGophkeeperService)(nil).SyncSecrets), ctx, userID)
}

// UpdateSecret mocks base method.
func (m *MockGophkeeperService) UpdateSecret(ctx context.Context, userID int64, id uuid.UUID, req domain.UpdateSecretRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, userID, id, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockGophkeeperServiceMockRecorder) UpdateSecret(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockGophkeeperService)(nil).UpdateSecret), ctx, userID, id, req)
}
